### ISSUE TITLE
perfection.czech api fails

### ISSUE THREAD

**Issue by za3k** [eddieantonio/perfection#6]
The API does not appear to accept a list of integers (matching `import perfection`)

```Traceback (most recent call last):
  File "/home/zachary/golf_css_colors.py", line 114, in <module>
    for h in possible_functions():
  File "/home/zachary/golf_css_colors.py", line 109, in possible_functions
    hf=perfection.czech.make_hash(xs)
  File "/home/zachary/.local/lib/python3.10/site-packages/perfection/czech.py", line 249, in make_hash
    return CzechHashBuilder(words, *args, **kwargs).hash_function
  File "/home/zachary/.local/lib/python3.10/site-packages/perfection/czech.py", line 42, in __init__
    self.indices = list(range(len(words[0])))
TypeError: object of type 'int' has no len()```

**Comment by eddieantonio** [comment]
Yep. Clearly I hadn't settled on an API that works for any hashable object, as would probably be a reasonable API expectation! This has been an issue for... \<checks notes\> [SIX YEARS?!?!?!](https://github.com/eddieantonio/perfection/commit/fa8a2970d0e494bc4de6d9be43472fa9210e3e67#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR73)

If I find time, I might revisit this repository and clean things up, but that probably won't be for another two weeks. I'll be honest, I kind of forget about this repo >.<
